[2023-11-21T01:20:58.533+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.load scheduled__2023-11-12T00:00:00+00:00 [queued]>
[2023-11-21T01:20:58.622+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.load scheduled__2023-11-12T00:00:00+00:00 [queued]>
[2023-11-21T01:20:58.624+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-21T01:20:58.764+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): load> on 2023-11-12 00:00:00+00:00
[2023-11-21T01:20:58.787+0000] {standard_task_runner.py:57} INFO - Started process 233 to run task
[2023-11-21T01:20:58.811+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'load', 'scheduled__2023-11-12T00:00:00+00:00', '--job-id', '39', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmp8qm6m1z2']
[2023-11-21T01:20:58.896+0000] {standard_task_runner.py:85} INFO - Job 39: Subtask load
[2023-11-21T01:20:59.409+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.load scheduled__2023-11-12T00:00:00+00:00 [running]> on host f31a30014ab0
[2023-11-21T01:21:09.803+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2023-11-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-12T00:00:00+00:00'
[2023-11-21T01:21:09.945+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ETL/load.py", line 11, in load_data
    data_to_staging(filename, engine)
  File "/opt/airflow/dags/ETL/load.py", line 19, in data_to_staging
    data = pd.read_parquet(filename)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parquet.py", line 509, in read_parquet
    return impl.read(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parquet.py", line 220, in read
    path_or_handle, handles, kwargs["filesystem"] = _get_path_or_handle(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parquet.py", line 110, in _get_path_or_handle
    handles = get_handle(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/common.py", line 868, in get_handle
    handle = open(handle, ioargs.mode)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/data/2023-11-12/processed/transformed_shelter_data.parquet'
[2023-11-21T01:21:10.007+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=outcomes_dag, task_id=load, execution_date=20231112T000000, start_date=20231121T012058, end_date=20231121T012110
[2023-11-21T01:21:10.057+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 39 for task load ([Errno 2] No such file or directory: '/opt/airflow/data/2023-11-12/processed/transformed_shelter_data.parquet'; 233)
[2023-11-21T01:21:10.166+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-21T01:21:10.490+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-11-21T02:36:23.442+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.load scheduled__2023-11-12T00:00:00+00:00 [queued]>
[2023-11-21T02:36:23.507+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.load scheduled__2023-11-12T00:00:00+00:00 [queued]>
[2023-11-21T02:36:23.522+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-21T02:36:23.618+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): load> on 2023-11-12 00:00:00+00:00
[2023-11-21T02:36:23.666+0000] {standard_task_runner.py:57} INFO - Started process 223 to run task
[2023-11-21T02:36:23.700+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'load', 'scheduled__2023-11-12T00:00:00+00:00', '--job-id', '43', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmpqzo706xb']
[2023-11-21T02:36:23.730+0000] {standard_task_runner.py:85} INFO - Job 43: Subtask load
[2023-11-21T02:36:24.136+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.load scheduled__2023-11-12T00:00:00+00:00 [running]> on host b875fa978b1e
[2023-11-21T02:36:27.486+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2023-11-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-12T00:00:00+00:00'
[2023-11-21T02:36:28.831+0000] {logging_mixin.py:154} INFO - Data is in Staging Table...
[2023-11-21T02:36:28.856+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ETL/load.py", line 13, in load_data
    execute_sql_script(engine)
  File "/opt/airflow/dags/ETL/load.py", line 38, in execute_sql_script
    with open(script_path, 'r') as file:
FileNotFoundError: [Errno 2] No such file or directory: '/dags/ETL/data_insertion.sql'
[2023-11-21T02:36:28.903+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=outcomes_dag, task_id=load, execution_date=20231112T000000, start_date=20231121T023623, end_date=20231121T023628
[2023-11-21T02:36:28.929+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 43 for task load ([Errno 2] No such file or directory: '/dags/ETL/data_insertion.sql'; 223)
[2023-11-21T02:36:28.985+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-21T02:36:29.018+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-11-22T07:54:06.614+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.Load scheduled__2023-11-12T00:00:00+00:00 [queued]>
[2023-11-22T07:54:06.637+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.Load scheduled__2023-11-12T00:00:00+00:00 [queued]>
[2023-11-22T07:54:06.643+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 4
[2023-11-22T07:54:06.711+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): Load> on 2023-11-12 00:00:00+00:00
[2023-11-22T07:54:06.753+0000] {standard_task_runner.py:57} INFO - Started process 364 to run task
[2023-11-22T07:54:06.842+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'Load', 'scheduled__2023-11-12T00:00:00+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmp3sp67v3m']
[2023-11-22T07:54:06.870+0000] {standard_task_runner.py:85} INFO - Job 35: Subtask Load
[2023-11-22T07:54:07.153+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.Load scheduled__2023-11-12T00:00:00+00:00 [running]> on host 6318e996d951
[2023-11-22T07:54:07.445+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='Load' AIRFLOW_CTX_EXECUTION_DATE='2023-11-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-12T00:00:00+00:00'
[2023-11-22T07:54:07.457+0000] {logging_mixin.py:154} INFO - Getting data from Cloud Storage
[2023-11-22T07:54:10.232+0000] {logging_mixin.py:154} INFO - Data is in Staging Table...
[2023-11-22T07:54:10.242+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-22T07:54:10.361+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=outcomes_dag, task_id=Load, execution_date=20231112T000000, start_date=20231122T075406, end_date=20231122T075410
[2023-11-22T07:54:10.896+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-23T01:49:42.247+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.Load scheduled__2023-11-12T00:00:00+00:00 [queued]>
[2023-11-23T01:49:42.314+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.Load scheduled__2023-11-12T00:00:00+00:00 [queued]>
[2023-11-23T01:49:42.323+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 4
[2023-11-23T01:49:42.390+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): Load> on 2023-11-12 00:00:00+00:00
[2023-11-23T01:49:42.548+0000] {standard_task_runner.py:57} INFO - Started process 203 to run task
[2023-11-23T01:49:42.593+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'Load', 'scheduled__2023-11-12T00:00:00+00:00', '--job-id', '44', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmp8n8svtyb']
[2023-11-23T01:49:42.644+0000] {standard_task_runner.py:85} INFO - Job 44: Subtask Load
[2023-11-23T01:49:42.852+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.Load scheduled__2023-11-12T00:00:00+00:00 [running]> on host d15d3caa5b00
[2023-11-23T01:49:43.085+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='Load' AIRFLOW_CTX_EXECUTION_DATE='2023-11-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-12T00:00:00+00:00'
[2023-11-23T01:49:43.094+0000] {logging_mixin.py:154} INFO - Getting data from Cloud Storage
[2023-11-23T01:49:44.191+0000] {logging_mixin.py:154} INFO - Data is in Staging Table...
[2023-11-23T01:49:44.197+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-23T01:49:44.234+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=outcomes_dag, task_id=Load, execution_date=20231112T000000, start_date=20231123T014942, end_date=20231123T014944
[2023-11-23T01:49:44.366+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-23T03:40:49.648+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.Load scheduled__2023-11-12T00:00:00+00:00 [queued]>
[2023-11-23T03:40:49.674+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.Load scheduled__2023-11-12T00:00:00+00:00 [queued]>
[2023-11-23T03:40:49.681+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 4
[2023-11-23T03:40:49.729+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): Load> on 2023-11-12 00:00:00+00:00
[2023-11-23T03:40:49.749+0000] {standard_task_runner.py:57} INFO - Started process 189 to run task
[2023-11-23T03:40:49.781+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'Load', 'scheduled__2023-11-12T00:00:00+00:00', '--job-id', '38', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmpum83hdgv']
[2023-11-23T03:40:49.812+0000] {standard_task_runner.py:85} INFO - Job 38: Subtask Load
[2023-11-23T03:40:50.029+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.Load scheduled__2023-11-12T00:00:00+00:00 [running]> on host e647c96745b0
[2023-11-23T03:40:50.245+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='Load' AIRFLOW_CTX_EXECUTION_DATE='2023-11-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-12T00:00:00+00:00'
[2023-11-23T03:40:50.249+0000] {logging_mixin.py:154} INFO - Getting data from Cloud Storage
[2023-11-23T03:40:51.566+0000] {logging_mixin.py:154} INFO - Data is in Staging Area...
[2023-11-23T03:40:51.568+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-23T03:40:51.616+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=outcomes_dag, task_id=Load, execution_date=20231112T000000, start_date=20231123T034049, end_date=20231123T034051
[2023-11-23T03:40:51.708+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
