[2023-11-21T01:20:11.833+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.load scheduled__2023-11-01T00:00:00+00:00 [queued]>
[2023-11-21T01:20:11.895+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.load scheduled__2023-11-01T00:00:00+00:00 [queued]>
[2023-11-21T01:20:11.902+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-21T01:20:11.971+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): load> on 2023-11-01 00:00:00+00:00
[2023-11-21T01:20:12.006+0000] {standard_task_runner.py:57} INFO - Started process 88 to run task
[2023-11-21T01:20:12.075+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'load', 'scheduled__2023-11-01T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmpm6hxnsss']
[2023-11-21T01:20:12.274+0000] {standard_task_runner.py:85} INFO - Job 4: Subtask load
[2023-11-21T01:20:13.491+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.load scheduled__2023-11-01T00:00:00+00:00 [running]> on host f31a30014ab0
[2023-11-21T01:20:27.012+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2023-11-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-01T00:00:00+00:00'
[2023-11-21T01:20:27.062+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ETL/load.py", line 11, in load_data
    data_to_staging(filename, engine)
  File "/opt/airflow/dags/ETL/load.py", line 19, in data_to_staging
    data = pd.read_parquet(filename)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parquet.py", line 509, in read_parquet
    return impl.read(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parquet.py", line 220, in read
    path_or_handle, handles, kwargs["filesystem"] = _get_path_or_handle(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parquet.py", line 110, in _get_path_or_handle
    handles = get_handle(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/common.py", line 868, in get_handle
    handle = open(handle, ioargs.mode)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/data/2023-11-01/processed/transformed_shelter_data.parquet'
[2023-11-21T01:20:27.091+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=outcomes_dag, task_id=load, execution_date=20231101T000000, start_date=20231121T012011, end_date=20231121T012027
[2023-11-21T01:20:27.145+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 4 for task load ([Errno 2] No such file or directory: '/opt/airflow/data/2023-11-01/processed/transformed_shelter_data.parquet'; 88)
[2023-11-21T01:20:27.307+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-21T01:20:27.729+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-11-21T02:36:04.266+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.load scheduled__2023-11-01T00:00:00+00:00 [queued]>
[2023-11-21T02:36:04.304+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.load scheduled__2023-11-01T00:00:00+00:00 [queued]>
[2023-11-21T02:36:04.304+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-21T02:36:04.401+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): load> on 2023-11-01 00:00:00+00:00
[2023-11-21T02:36:04.409+0000] {standard_task_runner.py:57} INFO - Started process 88 to run task
[2023-11-21T02:36:04.423+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'load', 'scheduled__2023-11-01T00:00:00+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmpc463hyfe']
[2023-11-21T02:36:04.462+0000] {standard_task_runner.py:85} INFO - Job 7: Subtask load
[2023-11-21T02:36:04.694+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.load scheduled__2023-11-01T00:00:00+00:00 [running]> on host b875fa978b1e
[2023-11-21T02:36:09.012+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2023-11-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-01T00:00:00+00:00'
[2023-11-21T02:36:09.091+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ETL/load.py", line 11, in load_data
    data_to_staging(filename, engine)
  File "/opt/airflow/dags/ETL/load.py", line 19, in data_to_staging
    data = pd.read_parquet(filename)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parquet.py", line 509, in read_parquet
    return impl.read(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parquet.py", line 220, in read
    path_or_handle, handles, kwargs["filesystem"] = _get_path_or_handle(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parquet.py", line 110, in _get_path_or_handle
    handles = get_handle(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/common.py", line 868, in get_handle
    handle = open(handle, ioargs.mode)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/data/2023-11-01/processed/transformed_shelter_data.parquet'
[2023-11-21T02:36:09.139+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=outcomes_dag, task_id=load, execution_date=20231101T000000, start_date=20231121T023604, end_date=20231121T023609
[2023-11-21T02:36:09.156+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 7 for task load ([Errno 2] No such file or directory: '/opt/airflow/data/2023-11-01/processed/transformed_shelter_data.parquet'; 88)
[2023-11-21T02:36:09.348+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-21T02:36:09.967+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-11-22T07:54:06.542+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.Load scheduled__2023-11-01T00:00:00+00:00 [queued]>
[2023-11-22T07:54:06.565+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.Load scheduled__2023-11-01T00:00:00+00:00 [queued]>
[2023-11-22T07:54:06.568+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 4
[2023-11-22T07:54:06.610+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): Load> on 2023-11-01 00:00:00+00:00
[2023-11-22T07:54:06.639+0000] {standard_task_runner.py:57} INFO - Started process 362 to run task
[2023-11-22T07:54:06.691+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'Load', 'scheduled__2023-11-01T00:00:00+00:00', '--job-id', '39', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmp3v114nxf']
[2023-11-22T07:54:06.727+0000] {standard_task_runner.py:85} INFO - Job 39: Subtask Load
[2023-11-22T07:54:07.137+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.Load scheduled__2023-11-01T00:00:00+00:00 [running]> on host 6318e996d951
[2023-11-22T07:54:07.497+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='Load' AIRFLOW_CTX_EXECUTION_DATE='2023-11-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-01T00:00:00+00:00'
[2023-11-22T07:54:07.510+0000] {logging_mixin.py:154} INFO - Getting data from Cloud Storage
[2023-11-22T07:54:10.115+0000] {logging_mixin.py:154} INFO - Data is in Staging Table...
[2023-11-22T07:54:10.160+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-22T07:54:10.313+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=outcomes_dag, task_id=Load, execution_date=20231101T000000, start_date=20231122T075406, end_date=20231122T075410
[2023-11-22T07:54:10.846+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-23T01:49:39.133+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.Load scheduled__2023-11-01T00:00:00+00:00 [queued]>
[2023-11-23T01:49:39.157+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.Load scheduled__2023-11-01T00:00:00+00:00 [queued]>
[2023-11-23T01:49:39.159+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 4
[2023-11-23T01:49:39.269+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): Load> on 2023-11-01 00:00:00+00:00
[2023-11-23T01:49:39.278+0000] {standard_task_runner.py:57} INFO - Started process 194 to run task
[2023-11-23T01:49:39.292+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'Load', 'scheduled__2023-11-01T00:00:00+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmpqamnp9gj']
[2023-11-23T01:49:39.302+0000] {standard_task_runner.py:85} INFO - Job 36: Subtask Load
[2023-11-23T01:49:39.516+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.Load scheduled__2023-11-01T00:00:00+00:00 [running]> on host d15d3caa5b00
[2023-11-23T01:49:39.716+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='Load' AIRFLOW_CTX_EXECUTION_DATE='2023-11-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-01T00:00:00+00:00'
[2023-11-23T01:49:39.720+0000] {logging_mixin.py:154} INFO - Getting data from Cloud Storage
[2023-11-23T01:49:40.847+0000] {logging_mixin.py:154} INFO - Data is in Staging Table...
[2023-11-23T01:49:40.858+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-23T01:49:40.927+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=outcomes_dag, task_id=Load, execution_date=20231101T000000, start_date=20231123T014939, end_date=20231123T014940
[2023-11-23T01:49:41.134+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-23T03:40:49.339+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.Load scheduled__2023-11-01T00:00:00+00:00 [queued]>
[2023-11-23T03:40:49.402+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.Load scheduled__2023-11-01T00:00:00+00:00 [queued]>
[2023-11-23T03:40:49.424+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 4
[2023-11-23T03:40:49.510+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): Load> on 2023-11-01 00:00:00+00:00
[2023-11-23T03:40:49.551+0000] {standard_task_runner.py:57} INFO - Started process 188 to run task
[2023-11-23T03:40:49.567+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'Load', 'scheduled__2023-11-01T00:00:00+00:00', '--job-id', '37', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmpz2ie_32m']
[2023-11-23T03:40:49.576+0000] {standard_task_runner.py:85} INFO - Job 37: Subtask Load
[2023-11-23T03:40:49.734+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.Load scheduled__2023-11-01T00:00:00+00:00 [running]> on host e647c96745b0
[2023-11-23T03:40:50.005+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='Load' AIRFLOW_CTX_EXECUTION_DATE='2023-11-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-01T00:00:00+00:00'
[2023-11-23T03:40:50.009+0000] {logging_mixin.py:154} INFO - Getting data from Cloud Storage
[2023-11-23T03:40:51.331+0000] {logging_mixin.py:154} INFO - Data is in Staging Area...
[2023-11-23T03:40:51.339+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-23T03:40:51.410+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=outcomes_dag, task_id=Load, execution_date=20231101T000000, start_date=20231123T034049, end_date=20231123T034051
[2023-11-23T03:40:51.529+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
