[2023-11-21T01:20:56.222+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.load scheduled__2023-11-11T00:00:00+00:00 [queued]>
[2023-11-21T01:20:56.237+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.load scheduled__2023-11-11T00:00:00+00:00 [queued]>
[2023-11-21T01:20:56.238+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-21T01:20:56.295+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): load> on 2023-11-11 00:00:00+00:00
[2023-11-21T01:20:56.350+0000] {standard_task_runner.py:57} INFO - Started process 227 to run task
[2023-11-21T01:20:56.443+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'load', 'scheduled__2023-11-11T00:00:00+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmpaotjjvgy']
[2023-11-21T01:20:56.505+0000] {standard_task_runner.py:85} INFO - Job 35: Subtask load
[2023-11-21T01:20:57.018+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.load scheduled__2023-11-11T00:00:00+00:00 [running]> on host f31a30014ab0
[2023-11-21T01:21:08.765+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2023-11-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-11T00:00:00+00:00'
[2023-11-21T01:21:09.627+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ETL/load.py", line 11, in load_data
    data_to_staging(filename, engine)
  File "/opt/airflow/dags/ETL/load.py", line 19, in data_to_staging
    data = pd.read_parquet(filename)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parquet.py", line 509, in read_parquet
    return impl.read(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parquet.py", line 220, in read
    path_or_handle, handles, kwargs["filesystem"] = _get_path_or_handle(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parquet.py", line 110, in _get_path_or_handle
    handles = get_handle(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/common.py", line 868, in get_handle
    handle = open(handle, ioargs.mode)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/data/2023-11-11/processed/transformed_shelter_data.parquet'
[2023-11-21T01:21:09.794+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=outcomes_dag, task_id=load, execution_date=20231111T000000, start_date=20231121T012056, end_date=20231121T012109
[2023-11-21T01:21:09.952+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 35 for task load ([Errno 2] No such file or directory: '/opt/airflow/data/2023-11-11/processed/transformed_shelter_data.parquet'; 227)
[2023-11-21T01:21:10.105+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-21T01:21:10.437+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-11-21T02:36:22.275+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.load scheduled__2023-11-11T00:00:00+00:00 [queued]>
[2023-11-21T02:36:22.295+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.load scheduled__2023-11-11T00:00:00+00:00 [queued]>
[2023-11-21T02:36:22.296+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-21T02:36:22.321+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): load> on 2023-11-11 00:00:00+00:00
[2023-11-21T02:36:22.337+0000] {standard_task_runner.py:57} INFO - Started process 207 to run task
[2023-11-21T02:36:22.363+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'load', 'scheduled__2023-11-11T00:00:00+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmpe7z5_pvz']
[2023-11-21T02:36:22.389+0000] {standard_task_runner.py:85} INFO - Job 35: Subtask load
[2023-11-21T02:36:22.562+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.load scheduled__2023-11-11T00:00:00+00:00 [running]> on host b875fa978b1e
[2023-11-21T02:36:27.539+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2023-11-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-11T00:00:00+00:00'
[2023-11-21T02:36:28.781+0000] {logging_mixin.py:154} INFO - Data is in Staging Table...
[2023-11-21T02:36:28.820+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ETL/load.py", line 13, in load_data
    execute_sql_script(engine)
  File "/opt/airflow/dags/ETL/load.py", line 38, in execute_sql_script
    with open(script_path, 'r') as file:
FileNotFoundError: [Errno 2] No such file or directory: '/dags/ETL/data_insertion.sql'
[2023-11-21T02:36:28.889+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=outcomes_dag, task_id=load, execution_date=20231111T000000, start_date=20231121T023622, end_date=20231121T023628
[2023-11-21T02:36:28.927+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 35 for task load ([Errno 2] No such file or directory: '/dags/ETL/data_insertion.sql'; 207)
[2023-11-21T02:36:28.986+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-21T02:36:29.063+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-11-22T07:54:14.000+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.Load scheduled__2023-11-11T00:00:00+00:00 [queued]>
[2023-11-22T07:54:14.047+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.Load scheduled__2023-11-11T00:00:00+00:00 [queued]>
[2023-11-22T07:54:14.047+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 4
[2023-11-22T07:54:14.134+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): Load> on 2023-11-11 00:00:00+00:00
[2023-11-22T07:54:14.208+0000] {standard_task_runner.py:57} INFO - Started process 403 to run task
[2023-11-22T07:54:14.317+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'Load', 'scheduled__2023-11-11T00:00:00+00:00', '--job-id', '49', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmp4701a13g']
[2023-11-22T07:54:14.394+0000] {standard_task_runner.py:85} INFO - Job 49: Subtask Load
[2023-11-22T07:54:14.716+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.Load scheduled__2023-11-11T00:00:00+00:00 [running]> on host 6318e996d951
[2023-11-22T07:54:14.957+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='Load' AIRFLOW_CTX_EXECUTION_DATE='2023-11-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-11T00:00:00+00:00'
[2023-11-22T07:54:14.963+0000] {logging_mixin.py:154} INFO - Getting data from Cloud Storage
[2023-11-22T07:54:16.628+0000] {logging_mixin.py:154} INFO - Data is in Staging Table...
[2023-11-22T07:54:16.635+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-22T07:54:16.719+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=outcomes_dag, task_id=Load, execution_date=20231111T000000, start_date=20231122T075414, end_date=20231122T075416
[2023-11-22T07:54:16.929+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-23T01:49:43.545+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.Load scheduled__2023-11-11T00:00:00+00:00 [queued]>
[2023-11-23T01:49:43.572+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.Load scheduled__2023-11-11T00:00:00+00:00 [queued]>
[2023-11-23T01:49:43.573+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 4
[2023-11-23T01:49:43.649+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): Load> on 2023-11-11 00:00:00+00:00
[2023-11-23T01:49:43.676+0000] {standard_task_runner.py:57} INFO - Started process 211 to run task
[2023-11-23T01:49:43.704+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'Load', 'scheduled__2023-11-11T00:00:00+00:00', '--job-id', '46', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmpszbzedfl']
[2023-11-23T01:49:43.777+0000] {standard_task_runner.py:85} INFO - Job 46: Subtask Load
[2023-11-23T01:49:43.995+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.Load scheduled__2023-11-11T00:00:00+00:00 [running]> on host d15d3caa5b00
[2023-11-23T01:49:44.183+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='Load' AIRFLOW_CTX_EXECUTION_DATE='2023-11-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-11T00:00:00+00:00'
[2023-11-23T01:49:44.206+0000] {logging_mixin.py:154} INFO - Getting data from Cloud Storage
[2023-11-23T01:49:45.956+0000] {logging_mixin.py:154} INFO - Data is in Staging Table...
[2023-11-23T01:49:45.964+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-23T01:49:46.068+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=outcomes_dag, task_id=Load, execution_date=20231111T000000, start_date=20231123T014943, end_date=20231123T014946
[2023-11-23T01:49:46.365+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-23T03:40:51.427+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.Load scheduled__2023-11-11T00:00:00+00:00 [queued]>
[2023-11-23T03:40:51.460+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.Load scheduled__2023-11-11T00:00:00+00:00 [queued]>
[2023-11-23T03:40:51.466+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 4
[2023-11-23T03:40:51.514+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): Load> on 2023-11-11 00:00:00+00:00
[2023-11-23T03:40:51.530+0000] {standard_task_runner.py:57} INFO - Started process 197 to run task
[2023-11-23T03:40:51.552+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'Load', 'scheduled__2023-11-11T00:00:00+00:00', '--job-id', '45', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmpg1ipfjxx']
[2023-11-23T03:40:51.571+0000] {standard_task_runner.py:85} INFO - Job 45: Subtask Load
[2023-11-23T03:40:51.775+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.Load scheduled__2023-11-11T00:00:00+00:00 [running]> on host e647c96745b0
[2023-11-23T03:40:52.189+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='Load' AIRFLOW_CTX_EXECUTION_DATE='2023-11-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-11T00:00:00+00:00'
[2023-11-23T03:40:52.215+0000] {logging_mixin.py:154} INFO - Getting data from Cloud Storage
[2023-11-23T03:40:53.291+0000] {logging_mixin.py:154} INFO - Data is in Staging Area...
[2023-11-23T03:40:53.301+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-23T03:40:53.346+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=outcomes_dag, task_id=Load, execution_date=20231111T000000, start_date=20231123T034051, end_date=20231123T034053
[2023-11-23T03:40:53.467+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
