[2023-11-22T03:09:56.600+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.Extract manual__2023-11-22T03:09:53.954584+00:00 [queued]>
[2023-11-22T03:09:56.604+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.Extract manual__2023-11-22T03:09:53.954584+00:00 [queued]>
[2023-11-22T03:09:56.605+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-22T03:09:56.611+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): Extract> on 2023-11-22 03:09:53.954584+00:00
[2023-11-22T03:09:56.620+0000] {standard_task_runner.py:57} INFO - Started process 357 to run task
[2023-11-22T03:09:56.624+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'Extract', 'manual__2023-11-22T03:09:53.954584+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmp9rzxud2_']
[2023-11-22T03:09:56.627+0000] {standard_task_runner.py:85} INFO - Job 19: Subtask Extract
[2023-11-22T03:09:56.665+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.Extract manual__2023-11-22T03:09:53.954584+00:00 [running]> on host 24b88ba10398
[2023-11-22T03:09:56.712+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='Extract' AIRFLOW_CTX_EXECUTION_DATE='2023-11-22T03:09:53.954584+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-22T03:09:53.954584+00:00'
[2023-11-22T03:09:59.548+0000] {logging_mixin.py:154} INFO - Data Deposited into Cloud Storage
[2023-11-22T03:09:59.550+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-22T03:09:59.571+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=outcomes_dag, task_id=Extract, execution_date=20231122T030953, start_date=20231122T030956, end_date=20231122T030959
[2023-11-22T03:09:59.614+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
