[2023-11-22T23:03:13.016+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.Load_to_staging scheduled__2023-11-02T00:00:00+00:00 [queued]>
[2023-11-22T23:03:13.022+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.Load_to_staging scheduled__2023-11-02T00:00:00+00:00 [queued]>
[2023-11-22T23:03:13.022+0000] {taskinstance.py:1361} INFO - Starting attempt 4 of 4
[2023-11-22T23:03:13.031+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): Load_to_staging> on 2023-11-02 00:00:00+00:00
[2023-11-22T23:03:13.037+0000] {standard_task_runner.py:57} INFO - Started process 423 to run task
[2023-11-22T23:03:13.050+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'Load_to_staging', 'scheduled__2023-11-02T00:00:00+00:00', '--job-id', '105', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmpiecjeahi']
[2023-11-22T23:03:13.054+0000] {standard_task_runner.py:85} INFO - Job 105: Subtask Load_to_staging
[2023-11-22T23:03:13.112+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.Load_to_staging scheduled__2023-11-02T00:00:00+00:00 [running]> on host 4b2f5af281f8
[2023-11-22T23:03:13.162+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='Load_to_staging' AIRFLOW_CTX_EXECUTION_DATE='2023-11-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-02T00:00:00+00:00'
[2023-11-22T23:03:14.250+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ETL/load.py", line 31, in data_to_staging
    load_job = client.load_table_from_uri(uri, table_ref, job_config=job_config)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/client.py", line 2375, in load_table_from_uri
    load_job._begin(retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/job/base.py", line 693, in _begin
    api_response = client._call_api(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/client.py", line 808, in _call_api
    return call()
  File "/home/airflow/.local/lib/python3.8/site-packages/google/api_core/retry.py", line 366, in retry_wrapped_func
    return retry_target(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/api_core/retry.py", line 204, in retry_target
    return target()
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/_http/__init__.py", line 494, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.NotFound: 404 POST https://bigquery.googleapis.com/bigquery/v2/projects/dcsc-warehouse/jobs?prettyPrint=false: Not found: Dataset dcsc-warehouse:dcsc-warehouse.shelter_warehouse_schema
[2023-11-22T23:03:14.262+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=outcomes_dag, task_id=Load_to_staging, execution_date=20231102T000000, start_date=20231122T230313, end_date=20231122T230314
[2023-11-22T23:03:14.268+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 105 for task Load_to_staging (404 POST https://bigquery.googleapis.com/bigquery/v2/projects/dcsc-warehouse/jobs?prettyPrint=false: Not found: Dataset dcsc-warehouse:dcsc-warehouse.shelter_warehouse_schema; 423)
[2023-11-22T23:03:14.313+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-22T23:23:35.037+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.Load_to_staging scheduled__2023-11-02T00:00:00+00:00 [queued]>
[2023-11-22T23:23:35.042+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.Load_to_staging scheduled__2023-11-02T00:00:00+00:00 [queued]>
[2023-11-22T23:23:35.042+0000] {taskinstance.py:1361} INFO - Starting attempt 4 of 4
[2023-11-22T23:23:35.047+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): Load_to_staging> on 2023-11-02 00:00:00+00:00
[2023-11-22T23:23:35.054+0000] {standard_task_runner.py:57} INFO - Started process 352 to run task
[2023-11-22T23:23:35.057+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'Load_to_staging', 'scheduled__2023-11-02T00:00:00+00:00', '--job-id', '83', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmpopd9ef43']
[2023-11-22T23:23:35.058+0000] {standard_task_runner.py:85} INFO - Job 83: Subtask Load_to_staging
[2023-11-22T23:23:35.106+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.Load_to_staging scheduled__2023-11-02T00:00:00+00:00 [running]> on host b410bfb4af5e
[2023-11-22T23:23:35.158+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='Load_to_staging' AIRFLOW_CTX_EXECUTION_DATE='2023-11-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-02T00:00:00+00:00'
[2023-11-22T23:23:35.397+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ETL/load.py", line 33, in data_to_staging
    load_job.result()  # Wait for the job to complete
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/job/base.py", line 922, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/api_core/future/polling.py", line 261, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 No schema specified on job or table.
[2023-11-22T23:23:35.405+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=outcomes_dag, task_id=Load_to_staging, execution_date=20231102T000000, start_date=20231122T232335, end_date=20231122T232335
[2023-11-22T23:23:35.411+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 83 for task Load_to_staging (400 No schema specified on job or table.; 352)
[2023-11-22T23:23:35.438+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-22T23:46:21.981+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.Load_to_staging scheduled__2023-11-02T00:00:00+00:00 [queued]>
[2023-11-22T23:46:21.989+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.Load_to_staging scheduled__2023-11-02T00:00:00+00:00 [queued]>
[2023-11-22T23:46:21.989+0000] {taskinstance.py:1361} INFO - Starting attempt 4 of 4
[2023-11-22T23:46:21.997+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): Load_to_staging> on 2023-11-02 00:00:00+00:00
[2023-11-22T23:46:22.004+0000] {standard_task_runner.py:57} INFO - Started process 365 to run task
[2023-11-22T23:46:22.008+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'Load_to_staging', 'scheduled__2023-11-02T00:00:00+00:00', '--job-id', '85', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmpamk5w1z6']
[2023-11-22T23:46:22.009+0000] {standard_task_runner.py:85} INFO - Job 85: Subtask Load_to_staging
[2023-11-22T23:46:22.067+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.Load_to_staging scheduled__2023-11-02T00:00:00+00:00 [running]> on host 371cae71aa63
[2023-11-22T23:46:22.137+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='Load_to_staging' AIRFLOW_CTX_EXECUTION_DATE='2023-11-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-02T00:00:00+00:00'
[2023-11-22T23:46:22.452+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ETL/load.py", line 33, in data_to_staging
    load_job.result()  # Wait for the job to complete
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/job/base.py", line 922, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/api_core/future/polling.py", line 261, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 No schema specified on job or table.
[2023-11-22T23:46:22.463+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=outcomes_dag, task_id=Load_to_staging, execution_date=20231102T000000, start_date=20231122T234621, end_date=20231122T234622
[2023-11-22T23:46:22.471+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 85 for task Load_to_staging (400 No schema specified on job or table.; 365)
[2023-11-22T23:46:22.508+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-23T00:42:58.978+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.Load_to_staging scheduled__2023-11-02T00:00:00+00:00 [queued]>
[2023-11-23T00:42:58.987+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.Load_to_staging scheduled__2023-11-02T00:00:00+00:00 [queued]>
[2023-11-23T00:42:58.987+0000] {taskinstance.py:1361} INFO - Starting attempt 4 of 4
[2023-11-23T00:42:58.998+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): Load_to_staging> on 2023-11-02 00:00:00+00:00
[2023-11-23T00:42:59.008+0000] {standard_task_runner.py:57} INFO - Started process 419 to run task
[2023-11-23T00:42:59.025+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'Load_to_staging', 'scheduled__2023-11-02T00:00:00+00:00', '--job-id', '102', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmph1voln1k']
[2023-11-23T00:42:59.052+0000] {standard_task_runner.py:85} INFO - Job 102: Subtask Load_to_staging
[2023-11-23T00:42:59.173+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.Load_to_staging scheduled__2023-11-02T00:00:00+00:00 [running]> on host 75913536581a
[2023-11-23T00:42:59.347+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='Load_to_staging' AIRFLOW_CTX_EXECUTION_DATE='2023-11-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-02T00:00:00+00:00'
[2023-11-23T00:43:00.102+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ETL/load.py", line 33, in data_to_staging
    load_job = client.load_table_from_uri(uri, table_ref, job_config=job_config)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/client.py", line 2375, in load_table_from_uri
    load_job._begin(retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/job/base.py", line 693, in _begin
    api_response = client._call_api(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/client.py", line 808, in _call_api
    return call()
  File "/home/airflow/.local/lib/python3.8/site-packages/google/api_core/retry.py", line 366, in retry_wrapped_func
    return retry_target(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/api_core/retry.py", line 204, in retry_target
    return target()
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/_http/__init__.py", line 494, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.NotFound: 404 POST https://bigquery.googleapis.com/bigquery/v2/projects/dcsc-warehouse/jobs?prettyPrint=false: Not found: Dataset dcsc-warehouse:dcsc-warehouse.shelter_warehouse_schema
[2023-11-23T00:43:00.143+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=outcomes_dag, task_id=Load_to_staging, execution_date=20231102T000000, start_date=20231123T004258, end_date=20231123T004300
[2023-11-23T00:43:00.156+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 102 for task Load_to_staging (404 POST https://bigquery.googleapis.com/bigquery/v2/projects/dcsc-warehouse/jobs?prettyPrint=false: Not found: Dataset dcsc-warehouse:dcsc-warehouse.shelter_warehouse_schema; 419)
[2023-11-23T00:43:00.233+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
