[2023-11-21T01:21:11.590+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.load scheduled__2023-11-14T00:00:00+00:00 [queued]>
[2023-11-21T01:21:11.667+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.load scheduled__2023-11-14T00:00:00+00:00 [queued]>
[2023-11-21T01:21:11.671+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-21T01:21:11.771+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): load> on 2023-11-14 00:00:00+00:00
[2023-11-21T01:21:11.860+0000] {standard_task_runner.py:57} INFO - Started process 267 to run task
[2023-11-21T01:21:11.965+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'load', 'scheduled__2023-11-14T00:00:00+00:00', '--job-id', '50', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmp8iibtz3w']
[2023-11-21T01:21:12.053+0000] {standard_task_runner.py:85} INFO - Job 50: Subtask load
[2023-11-21T01:21:12.329+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.load scheduled__2023-11-14T00:00:00+00:00 [running]> on host f31a30014ab0
[2023-11-21T01:21:14.630+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2023-11-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-14T00:00:00+00:00'
[2023-11-21T01:21:16.880+0000] {logging_mixin.py:154} INFO - Data is in Staging Table...
[2023-11-21T01:21:16.926+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ETL/load.py", line 13, in load_data
    execute_sql_script(engine)
  File "/opt/airflow/dags/ETL/load.py", line 38, in execute_sql_script
    with open(script_path, 'r') as file:
FileNotFoundError: [Errno 2] No such file or directory: '/ETL/data_insertion.sql'
[2023-11-21T01:21:17.256+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=outcomes_dag, task_id=load, execution_date=20231114T000000, start_date=20231121T012111, end_date=20231121T012117
[2023-11-21T01:21:17.393+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 50 for task load ([Errno 2] No such file or directory: '/ETL/data_insertion.sql'; 267)
[2023-11-21T01:21:17.543+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-21T01:21:17.615+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-11-21T02:36:25.196+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.load scheduled__2023-11-14T00:00:00+00:00 [queued]>
[2023-11-21T02:36:25.263+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.load scheduled__2023-11-14T00:00:00+00:00 [queued]>
[2023-11-21T02:36:25.274+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-21T02:36:25.346+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): load> on 2023-11-14 00:00:00+00:00
[2023-11-21T02:36:25.359+0000] {standard_task_runner.py:57} INFO - Started process 228 to run task
[2023-11-21T02:36:25.372+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'load', 'scheduled__2023-11-14T00:00:00+00:00', '--job-id', '45', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmpiyt2hi8j']
[2023-11-21T02:36:25.398+0000] {standard_task_runner.py:85} INFO - Job 45: Subtask load
[2023-11-21T02:36:25.729+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.load scheduled__2023-11-14T00:00:00+00:00 [running]> on host b875fa978b1e
[2023-11-21T02:36:28.111+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2023-11-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-14T00:00:00+00:00'
[2023-11-21T02:36:28.297+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ETL/load.py", line 11, in load_data
    data_to_staging(filename, engine)
  File "/opt/airflow/dags/ETL/load.py", line 19, in data_to_staging
    data = pd.read_parquet(filename)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parquet.py", line 509, in read_parquet
    return impl.read(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parquet.py", line 220, in read
    path_or_handle, handles, kwargs["filesystem"] = _get_path_or_handle(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parquet.py", line 110, in _get_path_or_handle
    handles = get_handle(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/common.py", line 868, in get_handle
    handle = open(handle, ioargs.mode)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/data/2023-11-14/processed/transformed_shelter_data.parquet'
[2023-11-21T02:36:28.362+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=outcomes_dag, task_id=load, execution_date=20231114T000000, start_date=20231121T023625, end_date=20231121T023628
[2023-11-21T02:36:28.433+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 45 for task load ([Errno 2] No such file or directory: '/opt/airflow/data/2023-11-14/processed/transformed_shelter_data.parquet'; 228)
[2023-11-21T02:36:28.515+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-21T02:36:28.689+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-11-22T07:54:04.822+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.Load scheduled__2023-11-14T00:00:00+00:00 [queued]>
[2023-11-22T07:54:04.919+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.Load scheduled__2023-11-14T00:00:00+00:00 [queued]>
[2023-11-22T07:54:04.944+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 4
[2023-11-22T07:54:05.154+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): Load> on 2023-11-14 00:00:00+00:00
[2023-11-22T07:54:05.237+0000] {standard_task_runner.py:57} INFO - Started process 356 to run task
[2023-11-22T07:54:05.259+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'Load', 'scheduled__2023-11-14T00:00:00+00:00', '--job-id', '37', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmpgakvd4ve']
[2023-11-22T07:54:05.334+0000] {standard_task_runner.py:85} INFO - Job 37: Subtask Load
[2023-11-22T07:54:05.860+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.Load scheduled__2023-11-14T00:00:00+00:00 [running]> on host 6318e996d951
[2023-11-22T07:54:06.301+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='Load' AIRFLOW_CTX_EXECUTION_DATE='2023-11-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-14T00:00:00+00:00'
[2023-11-22T07:54:06.325+0000] {logging_mixin.py:154} INFO - Getting data from Cloud Storage
[2023-11-22T07:54:08.410+0000] {logging_mixin.py:154} INFO - Data is in Staging Table...
[2023-11-22T07:54:08.421+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-22T07:54:08.462+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=outcomes_dag, task_id=Load, execution_date=20231114T000000, start_date=20231122T075404, end_date=20231122T075408
[2023-11-22T07:54:09.467+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-23T01:49:43.563+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.Load scheduled__2023-11-14T00:00:00+00:00 [queued]>
[2023-11-23T01:49:43.666+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.Load scheduled__2023-11-14T00:00:00+00:00 [queued]>
[2023-11-23T01:49:43.676+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 4
[2023-11-23T01:49:43.741+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): Load> on 2023-11-14 00:00:00+00:00
[2023-11-23T01:49:43.763+0000] {standard_task_runner.py:57} INFO - Started process 213 to run task
[2023-11-23T01:49:43.807+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'Load', 'scheduled__2023-11-14T00:00:00+00:00', '--job-id', '50', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmpgqijc8hz']
[2023-11-23T01:49:43.817+0000] {standard_task_runner.py:85} INFO - Job 50: Subtask Load
[2023-11-23T01:49:44.009+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.Load scheduled__2023-11-14T00:00:00+00:00 [running]> on host d15d3caa5b00
[2023-11-23T01:49:44.278+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='Load' AIRFLOW_CTX_EXECUTION_DATE='2023-11-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-14T00:00:00+00:00'
[2023-11-23T01:49:44.286+0000] {logging_mixin.py:154} INFO - Getting data from Cloud Storage
[2023-11-23T01:49:45.213+0000] {logging_mixin.py:154} INFO - Data is in Staging Table...
[2023-11-23T01:49:45.216+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-23T01:49:45.246+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=outcomes_dag, task_id=Load, execution_date=20231114T000000, start_date=20231123T014943, end_date=20231123T014945
[2023-11-23T01:49:45.393+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-23T03:40:51.624+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.Load scheduled__2023-11-14T00:00:00+00:00 [queued]>
[2023-11-23T03:40:51.658+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.Load scheduled__2023-11-14T00:00:00+00:00 [queued]>
[2023-11-23T03:40:51.660+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 4
[2023-11-23T03:40:51.717+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): Load> on 2023-11-14 00:00:00+00:00
[2023-11-23T03:40:51.733+0000] {standard_task_runner.py:57} INFO - Started process 199 to run task
[2023-11-23T03:40:51.783+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'Load', 'scheduled__2023-11-14T00:00:00+00:00', '--job-id', '48', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmpjmd0smji']
[2023-11-23T03:40:51.796+0000] {standard_task_runner.py:85} INFO - Job 48: Subtask Load
[2023-11-23T03:40:52.052+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.Load scheduled__2023-11-14T00:00:00+00:00 [running]> on host e647c96745b0
[2023-11-23T03:40:52.372+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='Load' AIRFLOW_CTX_EXECUTION_DATE='2023-11-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-14T00:00:00+00:00'
[2023-11-23T03:40:52.377+0000] {logging_mixin.py:154} INFO - Getting data from Cloud Storage
[2023-11-23T03:40:53.483+0000] {logging_mixin.py:154} INFO - Data is in Staging Area...
[2023-11-23T03:40:53.499+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-23T03:40:53.562+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=outcomes_dag, task_id=Load, execution_date=20231114T000000, start_date=20231123T034051, end_date=20231123T034053
[2023-11-23T03:40:53.696+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
