[2023-11-22T23:04:34.465+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.Load_to_staging scheduled__2023-11-21T00:00:00+00:00 [queued]>
[2023-11-22T23:04:34.471+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.Load_to_staging scheduled__2023-11-21T00:00:00+00:00 [queued]>
[2023-11-22T23:04:34.473+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 4
[2023-11-22T23:04:34.479+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): Load_to_staging> on 2023-11-21 00:00:00+00:00
[2023-11-22T23:04:34.485+0000] {standard_task_runner.py:57} INFO - Started process 529 to run task
[2023-11-22T23:04:34.490+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'Load_to_staging', 'scheduled__2023-11-21T00:00:00+00:00', '--job-id', '135', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmptwpgewmd']
[2023-11-22T23:04:34.493+0000] {standard_task_runner.py:85} INFO - Job 135: Subtask Load_to_staging
[2023-11-22T23:04:34.529+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.Load_to_staging scheduled__2023-11-21T00:00:00+00:00 [running]> on host 4b2f5af281f8
[2023-11-22T23:04:34.577+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='Load_to_staging' AIRFLOW_CTX_EXECUTION_DATE='2023-11-21T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-21T00:00:00+00:00'
[2023-11-22T23:04:35.843+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ETL/load.py", line 31, in data_to_staging
    load_job = client.load_table_from_uri(uri, table_ref, job_config=job_config)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/client.py", line 2375, in load_table_from_uri
    load_job._begin(retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/job/base.py", line 693, in _begin
    api_response = client._call_api(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/client.py", line 808, in _call_api
    return call()
  File "/home/airflow/.local/lib/python3.8/site-packages/google/api_core/retry.py", line 366, in retry_wrapped_func
    return retry_target(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/api_core/retry.py", line 204, in retry_target
    return target()
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/_http/__init__.py", line 494, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.NotFound: 404 POST https://bigquery.googleapis.com/bigquery/v2/projects/dcsc-warehouse/jobs?prettyPrint=false: Not found: Dataset dcsc-warehouse:dcsc-warehouse.shelter_warehouse_schema
[2023-11-22T23:04:35.863+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=outcomes_dag, task_id=Load_to_staging, execution_date=20231121T000000, start_date=20231122T230434, end_date=20231122T230435
[2023-11-22T23:04:35.872+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 135 for task Load_to_staging (404 POST https://bigquery.googleapis.com/bigquery/v2/projects/dcsc-warehouse/jobs?prettyPrint=false: Not found: Dataset dcsc-warehouse:dcsc-warehouse.shelter_warehouse_schema; 529)
[2023-11-22T23:04:35.888+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-22T23:47:45.555+0000] {taskinstance.py:1149} INFO - Dependencies not met for <TaskInstance: outcomes_dag.Load_to_staging scheduled__2023-11-21T00:00:00+00:00 [queued]>, dependency 'Trigger Rule' FAILED: Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_states=_UpstreamTIStates(success=0, skipped=0, failed=0, upstream_failed=0, removed=0, done=0, success_setup=0, skipped_setup=0), upstream_task_ids={'Initialize_wharehouse_schema'}
[2023-11-22T23:47:45.558+0000] {local_task_job_runner.py:154} INFO - Task is not able to be run
[2023-11-23T00:44:18.411+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.Load_to_staging scheduled__2023-11-21T00:00:00+00:00 [queued]>
[2023-11-23T00:44:18.416+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.Load_to_staging scheduled__2023-11-21T00:00:00+00:00 [queued]>
[2023-11-23T00:44:18.416+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 4
[2023-11-23T00:44:18.423+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): Load_to_staging> on 2023-11-21 00:00:00+00:00
[2023-11-23T00:44:18.431+0000] {standard_task_runner.py:57} INFO - Started process 560 to run task
[2023-11-23T00:44:18.434+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'Load_to_staging', 'scheduled__2023-11-21T00:00:00+00:00', '--job-id', '142', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmp4443lkti']
[2023-11-23T00:44:18.438+0000] {standard_task_runner.py:85} INFO - Job 142: Subtask Load_to_staging
[2023-11-23T00:44:18.509+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.Load_to_staging scheduled__2023-11-21T00:00:00+00:00 [running]> on host 75913536581a
[2023-11-23T00:44:18.585+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='Load_to_staging' AIRFLOW_CTX_EXECUTION_DATE='2023-11-21T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-21T00:00:00+00:00'
[2023-11-23T00:44:19.078+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ETL/load.py", line 35, in data_to_staging
    load_job.result()  # Wait for the job to complete
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/job/base.py", line 922, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/api_core/future/polling.py", line 261, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 No schema specified on job or table.
[2023-11-23T00:44:19.089+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=outcomes_dag, task_id=Load_to_staging, execution_date=20231121T000000, start_date=20231123T004418, end_date=20231123T004419
[2023-11-23T00:44:19.099+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 142 for task Load_to_staging (400 No schema specified on job or table.; 560)
[2023-11-23T00:44:19.134+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
