[2023-11-22T23:06:40.203+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.Load_to_staging scheduled__2023-11-21T00:00:00+00:00 [queued]>
[2023-11-22T23:06:40.207+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.Load_to_staging scheduled__2023-11-21T00:00:00+00:00 [queued]>
[2023-11-22T23:06:40.207+0000] {taskinstance.py:1361} INFO - Starting attempt 4 of 4
[2023-11-22T23:06:40.216+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): Load_to_staging> on 2023-11-21 00:00:00+00:00
[2023-11-22T23:06:40.228+0000] {standard_task_runner.py:57} INFO - Started process 592 to run task
[2023-11-22T23:06:40.232+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'Load_to_staging', 'scheduled__2023-11-21T00:00:00+00:00', '--job-id', '145', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmphbnsdp1w']
[2023-11-22T23:06:40.235+0000] {standard_task_runner.py:85} INFO - Job 145: Subtask Load_to_staging
[2023-11-22T23:06:40.295+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.Load_to_staging scheduled__2023-11-21T00:00:00+00:00 [running]> on host 4b2f5af281f8
[2023-11-22T23:06:40.363+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='Load_to_staging' AIRFLOW_CTX_EXECUTION_DATE='2023-11-21T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-21T00:00:00+00:00'
[2023-11-22T23:06:41.366+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ETL/load.py", line 33, in data_to_staging
    load_job.result()  # Wait for the job to complete
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/job/base.py", line 922, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/api_core/future/polling.py", line 261, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 No schema specified on job or table.
[2023-11-22T23:06:41.378+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=outcomes_dag, task_id=Load_to_staging, execution_date=20231121T000000, start_date=20231122T230640, end_date=20231122T230641
[2023-11-22T23:06:41.386+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 145 for task Load_to_staging (400 No schema specified on job or table.; 592)
[2023-11-22T23:06:41.405+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-22T23:49:51.137+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.Load_to_staging scheduled__2023-11-21T00:00:00+00:00 [queued]>
[2023-11-22T23:49:51.142+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.Load_to_staging scheduled__2023-11-21T00:00:00+00:00 [queued]>
[2023-11-22T23:49:51.142+0000] {taskinstance.py:1361} INFO - Starting attempt 4 of 4
[2023-11-22T23:49:51.150+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): Load_to_staging> on 2023-11-21 00:00:00+00:00
[2023-11-22T23:49:51.155+0000] {standard_task_runner.py:57} INFO - Started process 562 to run task
[2023-11-22T23:49:51.160+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'Load_to_staging', 'scheduled__2023-11-21T00:00:00+00:00', '--job-id', '136', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmpg6pgdcoy']
[2023-11-22T23:49:51.163+0000] {standard_task_runner.py:85} INFO - Job 136: Subtask Load_to_staging
[2023-11-22T23:49:51.213+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.Load_to_staging scheduled__2023-11-21T00:00:00+00:00 [running]> on host 371cae71aa63
[2023-11-22T23:49:51.284+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='Load_to_staging' AIRFLOW_CTX_EXECUTION_DATE='2023-11-21T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-21T00:00:00+00:00'
[2023-11-22T23:49:51.787+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ETL/load.py", line 33, in data_to_staging
    load_job.result()  # Wait for the job to complete
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/job/base.py", line 922, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/api_core/future/polling.py", line 261, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 No schema specified on job or table.
[2023-11-22T23:49:51.821+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=outcomes_dag, task_id=Load_to_staging, execution_date=20231121T000000, start_date=20231122T234951, end_date=20231122T234951
[2023-11-22T23:49:51.832+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 136 for task Load_to_staging (400 No schema specified on job or table.; 562)
[2023-11-22T23:49:51.870+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-23T00:46:25.634+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.Load_to_staging scheduled__2023-11-21T00:00:00+00:00 [queued]>
[2023-11-23T00:46:25.643+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.Load_to_staging scheduled__2023-11-21T00:00:00+00:00 [queued]>
[2023-11-23T00:46:25.643+0000] {taskinstance.py:1361} INFO - Starting attempt 4 of 7
[2023-11-23T00:46:25.651+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): Load_to_staging> on 2023-11-21 00:00:00+00:00
[2023-11-23T00:46:25.666+0000] {standard_task_runner.py:57} INFO - Started process 639 to run task
[2023-11-23T00:46:25.671+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'Load_to_staging', 'scheduled__2023-11-21T00:00:00+00:00', '--job-id', '159', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmp4f6vgzqz']
[2023-11-23T00:46:25.675+0000] {standard_task_runner.py:85} INFO - Job 159: Subtask Load_to_staging
[2023-11-23T00:46:25.727+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.Load_to_staging scheduled__2023-11-21T00:00:00+00:00 [running]> on host 75913536581a
[2023-11-23T00:46:25.801+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='Load_to_staging' AIRFLOW_CTX_EXECUTION_DATE='2023-11-21T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-21T00:00:00+00:00'
[2023-11-23T00:46:26.434+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ETL/load.py", line 35, in data_to_staging
    load_job.result()  # Wait for the job to complete
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/job/base.py", line 922, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/api_core/future/polling.py", line 261, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 No schema specified on job or table.
[2023-11-23T00:46:26.444+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=outcomes_dag, task_id=Load_to_staging, execution_date=20231121T000000, start_date=20231123T004625, end_date=20231123T004626
[2023-11-23T00:46:26.453+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 159 for task Load_to_staging (400 No schema specified on job or table.; 639)
[2023-11-23T00:46:26.462+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
