[2023-11-23T03:28:31.304+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.Insert scheduled__2023-11-22T00:00:00+00:00 [queued]>
[2023-11-23T03:28:31.308+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.Insert scheduled__2023-11-22T00:00:00+00:00 [queued]>
[2023-11-23T03:28:31.308+0000] {taskinstance.py:1361} INFO - Starting attempt 4 of 4
[2023-11-23T03:28:31.313+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): Insert> on 2023-11-22 00:00:00+00:00
[2023-11-23T03:28:31.318+0000] {standard_task_runner.py:57} INFO - Started process 662 to run task
[2023-11-23T03:28:31.321+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'Insert', 'scheduled__2023-11-22T00:00:00+00:00', '--job-id', '41', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmpgin_s366']
[2023-11-23T03:28:31.326+0000] {standard_task_runner.py:85} INFO - Job 41: Subtask Insert
[2023-11-23T03:28:31.372+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.Insert scheduled__2023-11-22T00:00:00+00:00 [running]> on host 1268bd8e5db0
[2023-11-23T03:28:31.419+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='Insert' AIRFLOW_CTX_EXECUTION_DATE='2023-11-22T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-22T00:00:00+00:00'
[2023-11-23T03:28:31.431+0000] {logging_mixin.py:154} INFO - Error executing SQL script: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "animal_dim_pkey"
DETAIL:  Key ("Animal ID")=(A887504) already exists.

[SQL: --- INSERT DATA INTO DIMENSION TABLES

--- Animal Dimension
INSERT INTO animal_dim ("Animal ID", "Name", "Animal Type", "Breed", "Color", "Sex", "DOB")
SELECT DISTINCT "Animal ID", "Name", "Animal Type", "Breed", "Color", "Sex", "DOB"
FROM outcomes_staging
WHERE "Animal ID" IS NOT NULL;

--- Outcomes Dimension
INSERT INTO outcome_type_dim ("Outcome Type")
SELECT DISTINCT "Outcome"
FROM outcomes_staging
WHERE "Outcome" IS NOT NULL;

--- Reproductive Status Dimension
INSERT INTO reproductive_status_dim ("Reproductive Status")
SELECT DISTINCT "Reproductive Status"
FROM outcomes_staging
WHERE "Reproductive Status" IS NOT NULL;

--- Date Dimension
INSERT INTO date_dim ("Date ID", "Day", "Month", "Year")
SELECT DISTINCT "Date ID", "Day", "Month", "Year"
FROM outcomes_staging
WHERE "Date ID" IS NOT NULL;




--- INSERT DATA INTO FACT TABLE
INSERT INTO outcomes_fct ("Date", "Animal", "Outcome", "Repo Status")
SELECT 
    dd."Date ID",
    ad."Animal ID",
    otd."Outcome ID",
    rsd."Status ID"
FROM outcomes_staging os
JOIN date_dim dd ON os."Date ID" = dd."Date ID"
JOIN animal_dim ad ON os."Animal ID" = ad."Animal ID"
JOIN outcome_type_dim otd ON os."Outcome" = otd."Outcome Type"
JOIN reproductive_status_dim rsd ON os."Reproductive Status" = rsd."Reproductive Status";

]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
[2023-11-23T03:28:31.431+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-23T03:28:31.438+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=outcomes_dag, task_id=Insert, execution_date=20231122T000000, start_date=20231123T032831, end_date=20231123T032831
[2023-11-23T03:28:31.453+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
