[2023-11-22T23:03:18.419+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.Load_to_staging scheduled__2023-11-14T00:00:00+00:00 [queued]>
[2023-11-22T23:03:18.439+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.Load_to_staging scheduled__2023-11-14T00:00:00+00:00 [queued]>
[2023-11-22T23:03:18.439+0000] {taskinstance.py:1361} INFO - Starting attempt 4 of 4
[2023-11-22T23:03:18.454+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): Load_to_staging> on 2023-11-14 00:00:00+00:00
[2023-11-22T23:03:18.460+0000] {standard_task_runner.py:57} INFO - Started process 448 to run task
[2023-11-22T23:03:18.467+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'Load_to_staging', 'scheduled__2023-11-14T00:00:00+00:00', '--job-id', '112', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmpiee7fqpt']
[2023-11-22T23:03:18.471+0000] {standard_task_runner.py:85} INFO - Job 112: Subtask Load_to_staging
[2023-11-22T23:03:18.539+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.Load_to_staging scheduled__2023-11-14T00:00:00+00:00 [running]> on host 4b2f5af281f8
[2023-11-22T23:03:18.636+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='Load_to_staging' AIRFLOW_CTX_EXECUTION_DATE='2023-11-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-14T00:00:00+00:00'
[2023-11-22T23:03:19.001+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ETL/load.py", line 31, in data_to_staging
    load_job = client.load_table_from_uri(uri, table_ref, job_config=job_config)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/client.py", line 2375, in load_table_from_uri
    load_job._begin(retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/job/base.py", line 693, in _begin
    api_response = client._call_api(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/client.py", line 808, in _call_api
    return call()
  File "/home/airflow/.local/lib/python3.8/site-packages/google/api_core/retry.py", line 366, in retry_wrapped_func
    return retry_target(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/api_core/retry.py", line 204, in retry_target
    return target()
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/_http/__init__.py", line 494, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.NotFound: 404 POST https://bigquery.googleapis.com/bigquery/v2/projects/dcsc-warehouse/jobs?prettyPrint=false: Not found: Dataset dcsc-warehouse:dcsc-warehouse.shelter_warehouse_schema
[2023-11-22T23:03:19.012+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=outcomes_dag, task_id=Load_to_staging, execution_date=20231114T000000, start_date=20231122T230318, end_date=20231122T230319
[2023-11-22T23:03:19.019+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 112 for task Load_to_staging (404 POST https://bigquery.googleapis.com/bigquery/v2/projects/dcsc-warehouse/jobs?prettyPrint=false: Not found: Dataset dcsc-warehouse:dcsc-warehouse.shelter_warehouse_schema; 448)
[2023-11-22T23:03:19.052+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-22T23:23:42.009+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.Load_to_staging scheduled__2023-11-14T00:00:00+00:00 [queued]>
[2023-11-22T23:23:42.044+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.Load_to_staging scheduled__2023-11-14T00:00:00+00:00 [queued]>
[2023-11-22T23:23:42.045+0000] {taskinstance.py:1361} INFO - Starting attempt 4 of 4
[2023-11-22T23:23:42.088+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): Load_to_staging> on 2023-11-14 00:00:00+00:00
[2023-11-22T23:23:42.152+0000] {standard_task_runner.py:57} INFO - Started process 400 to run task
[2023-11-22T23:23:42.184+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'Load_to_staging', 'scheduled__2023-11-14T00:00:00+00:00', '--job-id', '87', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmpzdjwyp0r']
[2023-11-22T23:23:42.195+0000] {standard_task_runner.py:85} INFO - Job 87: Subtask Load_to_staging
[2023-11-22T23:23:42.357+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.Load_to_staging scheduled__2023-11-14T00:00:00+00:00 [running]> on host b410bfb4af5e
[2023-11-22T23:23:42.559+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='Load_to_staging' AIRFLOW_CTX_EXECUTION_DATE='2023-11-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-14T00:00:00+00:00'
[2023-11-22T23:23:42.818+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ETL/load.py", line 33, in data_to_staging
    load_job.result()  # Wait for the job to complete
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/job/base.py", line 922, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/api_core/future/polling.py", line 261, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 No schema specified on job or table.
[2023-11-22T23:23:42.862+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=outcomes_dag, task_id=Load_to_staging, execution_date=20231114T000000, start_date=20231122T232342, end_date=20231122T232342
[2023-11-22T23:23:42.940+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 87 for task Load_to_staging (400 No schema specified on job or table.; 400)
[2023-11-22T23:23:43.026+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-22T23:46:33.191+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.Load_to_staging scheduled__2023-11-14T00:00:00+00:00 [queued]>
[2023-11-22T23:46:33.198+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.Load_to_staging scheduled__2023-11-14T00:00:00+00:00 [queued]>
[2023-11-22T23:46:33.199+0000] {taskinstance.py:1361} INFO - Starting attempt 4 of 4
[2023-11-22T23:46:33.208+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): Load_to_staging> on 2023-11-14 00:00:00+00:00
[2023-11-22T23:46:33.215+0000] {standard_task_runner.py:57} INFO - Started process 410 to run task
[2023-11-22T23:46:33.230+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'Load_to_staging', 'scheduled__2023-11-14T00:00:00+00:00', '--job-id', '98', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmpmvgb08e8']
[2023-11-22T23:46:33.232+0000] {standard_task_runner.py:85} INFO - Job 98: Subtask Load_to_staging
[2023-11-22T23:46:33.278+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.Load_to_staging scheduled__2023-11-14T00:00:00+00:00 [running]> on host 371cae71aa63
[2023-11-22T23:46:33.372+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='Load_to_staging' AIRFLOW_CTX_EXECUTION_DATE='2023-11-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-14T00:00:00+00:00'
[2023-11-22T23:46:33.638+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ETL/load.py", line 33, in data_to_staging
    load_job.result()  # Wait for the job to complete
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/job/base.py", line 922, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/api_core/future/polling.py", line 261, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 No schema specified on job or table.
[2023-11-22T23:46:33.651+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=outcomes_dag, task_id=Load_to_staging, execution_date=20231114T000000, start_date=20231122T234633, end_date=20231122T234633
[2023-11-22T23:46:33.659+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 98 for task Load_to_staging (400 No schema specified on job or table.; 410)
[2023-11-22T23:46:33.682+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-23T00:43:04.488+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.Load_to_staging scheduled__2023-11-14T00:00:00+00:00 [queued]>
[2023-11-23T00:43:04.529+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.Load_to_staging scheduled__2023-11-14T00:00:00+00:00 [queued]>
[2023-11-23T00:43:04.530+0000] {taskinstance.py:1361} INFO - Starting attempt 4 of 4
[2023-11-23T00:43:04.731+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): Load_to_staging> on 2023-11-14 00:00:00+00:00
[2023-11-23T00:43:04.790+0000] {standard_task_runner.py:57} INFO - Started process 465 to run task
[2023-11-23T00:43:04.811+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'Load_to_staging', 'scheduled__2023-11-14T00:00:00+00:00', '--job-id', '113', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmpwouj5ot_']
[2023-11-23T00:43:04.866+0000] {standard_task_runner.py:85} INFO - Job 113: Subtask Load_to_staging
[2023-11-23T00:43:05.068+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.Load_to_staging scheduled__2023-11-14T00:00:00+00:00 [running]> on host 75913536581a
[2023-11-23T00:43:05.469+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='Load_to_staging' AIRFLOW_CTX_EXECUTION_DATE='2023-11-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-14T00:00:00+00:00'
[2023-11-23T00:43:06.440+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ETL/load.py", line 35, in data_to_staging
    load_job.result()  # Wait for the job to complete
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/job/base.py", line 922, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/api_core/future/polling.py", line 261, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 No schema specified on job or table.
[2023-11-23T00:43:06.494+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=outcomes_dag, task_id=Load_to_staging, execution_date=20231114T000000, start_date=20231123T004304, end_date=20231123T004306
[2023-11-23T00:43:06.514+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 113 for task Load_to_staging (400 No schema specified on job or table.; 465)
[2023-11-23T00:43:06.566+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
