[2023-11-21T01:20:56.832+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.load scheduled__2023-11-10T00:00:00+00:00 [queued]>
[2023-11-21T01:20:56.878+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.load scheduled__2023-11-10T00:00:00+00:00 [queued]>
[2023-11-21T01:20:56.883+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-21T01:20:57.006+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): load> on 2023-11-10 00:00:00+00:00
[2023-11-21T01:20:57.043+0000] {standard_task_runner.py:57} INFO - Started process 229 to run task
[2023-11-21T01:20:57.099+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'load', 'scheduled__2023-11-10T00:00:00+00:00', '--job-id', '37', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmphoch6dol']
[2023-11-21T01:20:57.176+0000] {standard_task_runner.py:85} INFO - Job 37: Subtask load
[2023-11-21T01:20:57.947+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.load scheduled__2023-11-10T00:00:00+00:00 [running]> on host f31a30014ab0
[2023-11-21T01:21:08.424+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2023-11-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-10T00:00:00+00:00'
[2023-11-21T01:21:08.662+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ETL/load.py", line 11, in load_data
    data_to_staging(filename, engine)
  File "/opt/airflow/dags/ETL/load.py", line 19, in data_to_staging
    data = pd.read_parquet(filename)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parquet.py", line 509, in read_parquet
    return impl.read(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parquet.py", line 220, in read
    path_or_handle, handles, kwargs["filesystem"] = _get_path_or_handle(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parquet.py", line 110, in _get_path_or_handle
    handles = get_handle(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/common.py", line 868, in get_handle
    handle = open(handle, ioargs.mode)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/data/2023-11-10/processed/transformed_shelter_data.parquet'
[2023-11-21T01:21:08.729+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=outcomes_dag, task_id=load, execution_date=20231110T000000, start_date=20231121T012056, end_date=20231121T012108
[2023-11-21T01:21:08.831+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 37 for task load ([Errno 2] No such file or directory: '/opt/airflow/data/2023-11-10/processed/transformed_shelter_data.parquet'; 229)
[2023-11-21T01:21:09.617+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-21T01:21:09.943+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-11-21T02:36:22.829+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.load scheduled__2023-11-10T00:00:00+00:00 [queued]>
[2023-11-21T02:36:22.845+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.load scheduled__2023-11-10T00:00:00+00:00 [queued]>
[2023-11-21T02:36:22.846+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-21T02:36:22.904+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): load> on 2023-11-10 00:00:00+00:00
[2023-11-21T02:36:22.914+0000] {standard_task_runner.py:57} INFO - Started process 216 to run task
[2023-11-21T02:36:22.934+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'load', 'scheduled__2023-11-10T00:00:00+00:00', '--job-id', '40', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmpjicwf7c_']
[2023-11-21T02:36:22.939+0000] {standard_task_runner.py:85} INFO - Job 40: Subtask load
[2023-11-21T02:36:23.089+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.load scheduled__2023-11-10T00:00:00+00:00 [running]> on host b875fa978b1e
[2023-11-21T02:36:25.085+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2023-11-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-10T00:00:00+00:00'
[2023-11-21T02:36:25.149+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ETL/load.py", line 11, in load_data
    data_to_staging(filename, engine)
  File "/opt/airflow/dags/ETL/load.py", line 19, in data_to_staging
    data = pd.read_parquet(filename)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parquet.py", line 509, in read_parquet
    return impl.read(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parquet.py", line 220, in read
    path_or_handle, handles, kwargs["filesystem"] = _get_path_or_handle(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parquet.py", line 110, in _get_path_or_handle
    handles = get_handle(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/common.py", line 868, in get_handle
    handle = open(handle, ioargs.mode)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/data/2023-11-10/processed/transformed_shelter_data.parquet'
[2023-11-21T02:36:25.192+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=outcomes_dag, task_id=load, execution_date=20231110T000000, start_date=20231121T023622, end_date=20231121T023625
[2023-11-21T02:36:25.214+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 40 for task load ([Errno 2] No such file or directory: '/opt/airflow/data/2023-11-10/processed/transformed_shelter_data.parquet'; 216)
[2023-11-21T02:36:25.379+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-21T02:36:25.503+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-11-22T07:54:06.612+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.Load scheduled__2023-11-10T00:00:00+00:00 [queued]>
[2023-11-22T07:54:06.634+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.Load scheduled__2023-11-10T00:00:00+00:00 [queued]>
[2023-11-22T07:54:06.636+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 4
[2023-11-22T07:54:06.687+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): Load> on 2023-11-10 00:00:00+00:00
[2023-11-22T07:54:06.749+0000] {standard_task_runner.py:57} INFO - Started process 363 to run task
[2023-11-22T07:54:06.805+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'Load', 'scheduled__2023-11-10T00:00:00+00:00', '--job-id', '41', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmp2ymwv012']
[2023-11-22T07:54:06.840+0000] {standard_task_runner.py:85} INFO - Job 41: Subtask Load
[2023-11-22T07:54:07.299+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.Load scheduled__2023-11-10T00:00:00+00:00 [running]> on host 6318e996d951
[2023-11-22T07:54:07.677+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='Load' AIRFLOW_CTX_EXECUTION_DATE='2023-11-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-10T00:00:00+00:00'
[2023-11-22T07:54:07.694+0000] {logging_mixin.py:154} INFO - Getting data from Cloud Storage
[2023-11-22T07:54:09.162+0000] {logging_mixin.py:154} INFO - Data is in Staging Table...
[2023-11-22T07:54:09.166+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-22T07:54:09.202+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=outcomes_dag, task_id=Load, execution_date=20231110T000000, start_date=20231122T075406, end_date=20231122T075409
[2023-11-22T07:54:09.339+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-23T01:49:41.405+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.Load scheduled__2023-11-10T00:00:00+00:00 [queued]>
[2023-11-23T01:49:41.462+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.Load scheduled__2023-11-10T00:00:00+00:00 [queued]>
[2023-11-23T01:49:41.462+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 4
[2023-11-23T01:49:41.609+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): Load> on 2023-11-10 00:00:00+00:00
[2023-11-23T01:49:41.647+0000] {standard_task_runner.py:57} INFO - Started process 198 to run task
[2023-11-23T01:49:41.676+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'Load', 'scheduled__2023-11-10T00:00:00+00:00', '--job-id', '40', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmpmt4f1ra8']
[2023-11-23T01:49:41.731+0000] {standard_task_runner.py:85} INFO - Job 40: Subtask Load
[2023-11-23T01:49:41.951+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.Load scheduled__2023-11-10T00:00:00+00:00 [running]> on host d15d3caa5b00
[2023-11-23T01:49:42.311+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='Load' AIRFLOW_CTX_EXECUTION_DATE='2023-11-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-10T00:00:00+00:00'
[2023-11-23T01:49:42.348+0000] {logging_mixin.py:154} INFO - Getting data from Cloud Storage
[2023-11-23T01:49:43.828+0000] {logging_mixin.py:154} INFO - Data is in Staging Table...
[2023-11-23T01:49:43.843+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-23T01:49:43.899+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=outcomes_dag, task_id=Load, execution_date=20231110T000000, start_date=20231123T014941, end_date=20231123T014943
[2023-11-23T01:49:44.034+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-23T03:40:51.549+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.Load scheduled__2023-11-10T00:00:00+00:00 [queued]>
[2023-11-23T03:40:51.603+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.Load scheduled__2023-11-10T00:00:00+00:00 [queued]>
[2023-11-23T03:40:51.609+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 4
[2023-11-23T03:40:51.659+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): Load> on 2023-11-10 00:00:00+00:00
[2023-11-23T03:40:51.676+0000] {standard_task_runner.py:57} INFO - Started process 198 to run task
[2023-11-23T03:40:51.694+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'Load', 'scheduled__2023-11-10T00:00:00+00:00', '--job-id', '47', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmpixmvamba']
[2023-11-23T03:40:51.742+0000] {standard_task_runner.py:85} INFO - Job 47: Subtask Load
[2023-11-23T03:40:51.961+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.Load scheduled__2023-11-10T00:00:00+00:00 [running]> on host e647c96745b0
[2023-11-23T03:40:52.291+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='Load' AIRFLOW_CTX_EXECUTION_DATE='2023-11-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-10T00:00:00+00:00'
[2023-11-23T03:40:52.310+0000] {logging_mixin.py:154} INFO - Getting data from Cloud Storage
[2023-11-23T03:40:53.409+0000] {logging_mixin.py:154} INFO - Data is in Staging Area...
[2023-11-23T03:40:53.421+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-23T03:40:53.483+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=outcomes_dag, task_id=Load, execution_date=20231110T000000, start_date=20231123T034051, end_date=20231123T034053
[2023-11-23T03:40:53.651+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
