[2023-11-22T23:03:18.458+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.Load_to_staging scheduled__2023-11-16T00:00:00+00:00 [queued]>
[2023-11-22T23:03:18.463+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.Load_to_staging scheduled__2023-11-16T00:00:00+00:00 [queued]>
[2023-11-22T23:03:18.463+0000] {taskinstance.py:1361} INFO - Starting attempt 4 of 4
[2023-11-22T23:03:18.472+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): Load_to_staging> on 2023-11-16 00:00:00+00:00
[2023-11-22T23:03:18.480+0000] {standard_task_runner.py:57} INFO - Started process 449 to run task
[2023-11-22T23:03:18.492+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'Load_to_staging', 'scheduled__2023-11-16T00:00:00+00:00', '--job-id', '113', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmp50t3ijgr']
[2023-11-22T23:03:18.499+0000] {standard_task_runner.py:85} INFO - Job 113: Subtask Load_to_staging
[2023-11-22T23:03:18.564+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.Load_to_staging scheduled__2023-11-16T00:00:00+00:00 [running]> on host 4b2f5af281f8
[2023-11-22T23:03:18.670+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='Load_to_staging' AIRFLOW_CTX_EXECUTION_DATE='2023-11-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-16T00:00:00+00:00'
[2023-11-22T23:03:19.004+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ETL/load.py", line 31, in data_to_staging
    load_job = client.load_table_from_uri(uri, table_ref, job_config=job_config)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/client.py", line 2375, in load_table_from_uri
    load_job._begin(retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/job/base.py", line 693, in _begin
    api_response = client._call_api(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/client.py", line 808, in _call_api
    return call()
  File "/home/airflow/.local/lib/python3.8/site-packages/google/api_core/retry.py", line 366, in retry_wrapped_func
    return retry_target(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/api_core/retry.py", line 204, in retry_target
    return target()
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/_http/__init__.py", line 494, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.NotFound: 404 POST https://bigquery.googleapis.com/bigquery/v2/projects/dcsc-warehouse/jobs?prettyPrint=false: Not found: Dataset dcsc-warehouse:dcsc-warehouse.shelter_warehouse_schema
[2023-11-22T23:03:19.015+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=outcomes_dag, task_id=Load_to_staging, execution_date=20231116T000000, start_date=20231122T230318, end_date=20231122T230319
[2023-11-22T23:03:19.023+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 113 for task Load_to_staging (404 POST https://bigquery.googleapis.com/bigquery/v2/projects/dcsc-warehouse/jobs?prettyPrint=false: Not found: Dataset dcsc-warehouse:dcsc-warehouse.shelter_warehouse_schema; 449)
[2023-11-22T23:03:19.037+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-22T23:23:37.521+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.Load_to_staging scheduled__2023-11-16T00:00:00+00:00 [queued]>
[2023-11-22T23:23:37.525+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.Load_to_staging scheduled__2023-11-16T00:00:00+00:00 [queued]>
[2023-11-22T23:23:37.525+0000] {taskinstance.py:1361} INFO - Starting attempt 4 of 4
[2023-11-22T23:23:37.530+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): Load_to_staging> on 2023-11-16 00:00:00+00:00
[2023-11-22T23:23:37.534+0000] {standard_task_runner.py:57} INFO - Started process 357 to run task
[2023-11-22T23:23:37.537+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'Load_to_staging', 'scheduled__2023-11-16T00:00:00+00:00', '--job-id', '86', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmp8vnwdbf5']
[2023-11-22T23:23:37.538+0000] {standard_task_runner.py:85} INFO - Job 86: Subtask Load_to_staging
[2023-11-22T23:23:37.569+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.Load_to_staging scheduled__2023-11-16T00:00:00+00:00 [running]> on host b410bfb4af5e
[2023-11-22T23:23:37.609+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='Load_to_staging' AIRFLOW_CTX_EXECUTION_DATE='2023-11-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-16T00:00:00+00:00'
[2023-11-22T23:23:37.834+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ETL/load.py", line 33, in data_to_staging
    load_job.result()  # Wait for the job to complete
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/job/base.py", line 922, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/api_core/future/polling.py", line 261, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 No schema specified on job or table.
[2023-11-22T23:23:37.844+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=outcomes_dag, task_id=Load_to_staging, execution_date=20231116T000000, start_date=20231122T232337, end_date=20231122T232337
[2023-11-22T23:23:37.853+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 86 for task Load_to_staging (400 No schema specified on job or table.; 357)
[2023-11-22T23:23:37.884+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-22T23:46:25.350+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.Load_to_staging scheduled__2023-11-16T00:00:00+00:00 [queued]>
[2023-11-22T23:46:25.355+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.Load_to_staging scheduled__2023-11-16T00:00:00+00:00 [queued]>
[2023-11-22T23:46:25.355+0000] {taskinstance.py:1361} INFO - Starting attempt 4 of 4
[2023-11-22T23:46:25.360+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): Load_to_staging> on 2023-11-16 00:00:00+00:00
[2023-11-22T23:46:25.366+0000] {standard_task_runner.py:57} INFO - Started process 376 to run task
[2023-11-22T23:46:25.368+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'Load_to_staging', 'scheduled__2023-11-16T00:00:00+00:00', '--job-id', '90', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmp84bc0kyt']
[2023-11-22T23:46:25.369+0000] {standard_task_runner.py:85} INFO - Job 90: Subtask Load_to_staging
[2023-11-22T23:46:25.423+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.Load_to_staging scheduled__2023-11-16T00:00:00+00:00 [running]> on host 371cae71aa63
[2023-11-22T23:46:25.467+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='Load_to_staging' AIRFLOW_CTX_EXECUTION_DATE='2023-11-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-16T00:00:00+00:00'
[2023-11-22T23:46:25.734+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ETL/load.py", line 33, in data_to_staging
    load_job.result()  # Wait for the job to complete
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/job/base.py", line 922, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/api_core/future/polling.py", line 261, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 No schema specified on job or table.
[2023-11-22T23:46:25.748+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=outcomes_dag, task_id=Load_to_staging, execution_date=20231116T000000, start_date=20231122T234625, end_date=20231122T234625
[2023-11-22T23:46:25.755+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 90 for task Load_to_staging (400 No schema specified on job or table.; 376)
[2023-11-22T23:46:25.797+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-23T00:43:06.242+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.Load_to_staging scheduled__2023-11-16T00:00:00+00:00 [queued]>
[2023-11-23T00:43:06.272+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.Load_to_staging scheduled__2023-11-16T00:00:00+00:00 [queued]>
[2023-11-23T00:43:06.273+0000] {taskinstance.py:1361} INFO - Starting attempt 4 of 4
[2023-11-23T00:43:06.299+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): Load_to_staging> on 2023-11-16 00:00:00+00:00
[2023-11-23T00:43:06.327+0000] {standard_task_runner.py:57} INFO - Started process 472 to run task
[2023-11-23T00:43:06.344+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'Load_to_staging', 'scheduled__2023-11-16T00:00:00+00:00', '--job-id', '116', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmpr4yp6jys']
[2023-11-23T00:43:06.357+0000] {standard_task_runner.py:85} INFO - Job 116: Subtask Load_to_staging
[2023-11-23T00:43:06.507+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.Load_to_staging scheduled__2023-11-16T00:00:00+00:00 [running]> on host 75913536581a
[2023-11-23T00:43:06.672+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='Load_to_staging' AIRFLOW_CTX_EXECUTION_DATE='2023-11-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-16T00:00:00+00:00'
[2023-11-23T00:43:07.470+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ETL/load.py", line 35, in data_to_staging
    load_job.result()  # Wait for the job to complete
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/job/base.py", line 922, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/api_core/future/polling.py", line 261, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 No schema specified on job or table.
[2023-11-23T00:43:07.552+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=outcomes_dag, task_id=Load_to_staging, execution_date=20231116T000000, start_date=20231123T004306, end_date=20231123T004307
[2023-11-23T00:43:07.578+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 116 for task Load_to_staging (400 No schema specified on job or table.; 472)
[2023-11-23T00:43:07.637+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
