[2023-11-22T23:03:17.731+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.Load_to_staging scheduled__2023-11-06T00:00:00+00:00 [queued]>
[2023-11-22T23:03:17.757+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.Load_to_staging scheduled__2023-11-06T00:00:00+00:00 [queued]>
[2023-11-22T23:03:17.757+0000] {taskinstance.py:1361} INFO - Starting attempt 4 of 4
[2023-11-22T23:03:17.780+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): Load_to_staging> on 2023-11-06 00:00:00+00:00
[2023-11-22T23:03:17.802+0000] {standard_task_runner.py:57} INFO - Started process 442 to run task
[2023-11-22T23:03:17.815+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'Load_to_staging', 'scheduled__2023-11-06T00:00:00+00:00', '--job-id', '106', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmp89i_zmhe']
[2023-11-22T23:03:17.822+0000] {standard_task_runner.py:85} INFO - Job 106: Subtask Load_to_staging
[2023-11-22T23:03:18.042+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.Load_to_staging scheduled__2023-11-06T00:00:00+00:00 [running]> on host 4b2f5af281f8
[2023-11-22T23:03:18.275+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='Load_to_staging' AIRFLOW_CTX_EXECUTION_DATE='2023-11-06T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-06T00:00:00+00:00'
[2023-11-22T23:03:18.774+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ETL/load.py", line 31, in data_to_staging
    load_job = client.load_table_from_uri(uri, table_ref, job_config=job_config)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/client.py", line 2375, in load_table_from_uri
    load_job._begin(retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/job/base.py", line 693, in _begin
    api_response = client._call_api(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/client.py", line 808, in _call_api
    return call()
  File "/home/airflow/.local/lib/python3.8/site-packages/google/api_core/retry.py", line 366, in retry_wrapped_func
    return retry_target(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/api_core/retry.py", line 204, in retry_target
    return target()
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/_http/__init__.py", line 494, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.NotFound: 404 POST https://bigquery.googleapis.com/bigquery/v2/projects/dcsc-warehouse/jobs?prettyPrint=false: Not found: Dataset dcsc-warehouse:dcsc-warehouse.shelter_warehouse_schema
[2023-11-22T23:03:18.785+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=outcomes_dag, task_id=Load_to_staging, execution_date=20231106T000000, start_date=20231122T230317, end_date=20231122T230318
[2023-11-22T23:03:18.793+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 106 for task Load_to_staging (404 POST https://bigquery.googleapis.com/bigquery/v2/projects/dcsc-warehouse/jobs?prettyPrint=false: Not found: Dataset dcsc-warehouse:dcsc-warehouse.shelter_warehouse_schema; 442)
[2023-11-22T23:03:18.829+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-22T23:23:42.692+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.Load_to_staging scheduled__2023-11-06T00:00:00+00:00 [queued]>
[2023-11-22T23:23:42.705+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.Load_to_staging scheduled__2023-11-06T00:00:00+00:00 [queued]>
[2023-11-22T23:23:42.706+0000] {taskinstance.py:1361} INFO - Starting attempt 4 of 4
[2023-11-22T23:23:42.729+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): Load_to_staging> on 2023-11-06 00:00:00+00:00
[2023-11-22T23:23:42.738+0000] {standard_task_runner.py:57} INFO - Started process 402 to run task
[2023-11-22T23:23:42.751+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'Load_to_staging', 'scheduled__2023-11-06T00:00:00+00:00', '--job-id', '90', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmp_hrifqrq']
[2023-11-22T23:23:42.771+0000] {standard_task_runner.py:85} INFO - Job 90: Subtask Load_to_staging
[2023-11-22T23:23:43.013+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.Load_to_staging scheduled__2023-11-06T00:00:00+00:00 [running]> on host b410bfb4af5e
[2023-11-22T23:23:43.218+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='Load_to_staging' AIRFLOW_CTX_EXECUTION_DATE='2023-11-06T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-06T00:00:00+00:00'
[2023-11-22T23:23:43.455+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ETL/load.py", line 33, in data_to_staging
    load_job.result()  # Wait for the job to complete
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/job/base.py", line 922, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/api_core/future/polling.py", line 261, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 No schema specified on job or table.
[2023-11-22T23:23:43.511+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=outcomes_dag, task_id=Load_to_staging, execution_date=20231106T000000, start_date=20231122T232342, end_date=20231122T232343
[2023-11-22T23:23:43.546+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 90 for task Load_to_staging (400 No schema specified on job or table.; 402)
[2023-11-22T23:23:43.591+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-22T23:46:30.260+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.Load_to_staging scheduled__2023-11-06T00:00:00+00:00 [queued]>
[2023-11-22T23:46:30.300+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.Load_to_staging scheduled__2023-11-06T00:00:00+00:00 [queued]>
[2023-11-22T23:46:30.303+0000] {taskinstance.py:1361} INFO - Starting attempt 4 of 4
[2023-11-22T23:46:30.492+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): Load_to_staging> on 2023-11-06 00:00:00+00:00
[2023-11-22T23:46:30.586+0000] {standard_task_runner.py:57} INFO - Started process 397 to run task
[2023-11-22T23:46:30.635+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'Load_to_staging', 'scheduled__2023-11-06T00:00:00+00:00', '--job-id', '91', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmp_cwxg3ob']
[2023-11-22T23:46:30.649+0000] {standard_task_runner.py:85} INFO - Job 91: Subtask Load_to_staging
[2023-11-22T23:46:30.870+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.Load_to_staging scheduled__2023-11-06T00:00:00+00:00 [running]> on host 371cae71aa63
[2023-11-22T23:46:31.230+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='Load_to_staging' AIRFLOW_CTX_EXECUTION_DATE='2023-11-06T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-06T00:00:00+00:00'
[2023-11-22T23:46:31.563+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ETL/load.py", line 33, in data_to_staging
    load_job.result()  # Wait for the job to complete
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/job/base.py", line 922, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/api_core/future/polling.py", line 261, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 No schema specified on job or table.
[2023-11-22T23:46:31.611+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=outcomes_dag, task_id=Load_to_staging, execution_date=20231106T000000, start_date=20231122T234630, end_date=20231122T234631
[2023-11-22T23:46:31.678+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 91 for task Load_to_staging (400 No schema specified on job or table.; 397)
[2023-11-22T23:46:31.761+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-23T00:43:03.144+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.Load_to_staging scheduled__2023-11-06T00:00:00+00:00 [queued]>
[2023-11-23T00:43:03.213+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.Load_to_staging scheduled__2023-11-06T00:00:00+00:00 [queued]>
[2023-11-23T00:43:03.218+0000] {taskinstance.py:1361} INFO - Starting attempt 4 of 4
[2023-11-23T00:43:03.342+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): Load_to_staging> on 2023-11-06 00:00:00+00:00
[2023-11-23T00:43:03.365+0000] {standard_task_runner.py:57} INFO - Started process 458 to run task
[2023-11-23T00:43:03.394+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'Load_to_staging', 'scheduled__2023-11-06T00:00:00+00:00', '--job-id', '110', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmpnpu39te5']
[2023-11-23T00:43:03.400+0000] {standard_task_runner.py:85} INFO - Job 110: Subtask Load_to_staging
[2023-11-23T00:43:03.551+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.Load_to_staging scheduled__2023-11-06T00:00:00+00:00 [running]> on host 75913536581a
[2023-11-23T00:43:03.844+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='Load_to_staging' AIRFLOW_CTX_EXECUTION_DATE='2023-11-06T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-06T00:00:00+00:00'
[2023-11-23T00:43:04.819+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ETL/load.py", line 35, in data_to_staging
    load_job.result()  # Wait for the job to complete
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/job/base.py", line 922, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/api_core/future/polling.py", line 261, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 No schema specified on job or table.
[2023-11-23T00:43:04.986+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=outcomes_dag, task_id=Load_to_staging, execution_date=20231106T000000, start_date=20231123T004303, end_date=20231123T004304
[2023-11-23T00:43:05.077+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 110 for task Load_to_staging (400 No schema specified on job or table.; 458)
[2023-11-23T00:43:05.151+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
