[2023-11-22T05:47:52.435+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.Insert manual__2023-11-22T05:47:34.180273+00:00 [queued]>
[2023-11-22T05:47:52.449+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.Insert manual__2023-11-22T05:47:34.180273+00:00 [queued]>
[2023-11-22T05:47:52.450+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-22T05:47:52.467+0000] {taskinstance.py:1382} INFO - Executing <Task(PostgresOperator): Insert> on 2023-11-22 05:47:34.180273+00:00
[2023-11-22T05:47:52.477+0000] {standard_task_runner.py:57} INFO - Started process 202 to run task
[2023-11-22T05:47:52.496+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'Insert', 'manual__2023-11-22T05:47:34.180273+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmp_353w1l_']
[2023-11-22T05:47:52.505+0000] {standard_task_runner.py:85} INFO - Job 29: Subtask Insert
[2023-11-22T05:47:52.580+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.Insert manual__2023-11-22T05:47:34.180273+00:00 [running]> on host 6e2e77b078ed
[2023-11-22T05:47:52.651+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='Insert' AIRFLOW_CTX_EXECUTION_DATE='2023-11-22T05:47:34.180273+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-22T05:47:34.180273+00:00'
[2023-11-22T05:47:52.652+0000] {sql.py:274} INFO - Executing: --- INSERT DATA INTO DIMENSION TABLES

--- Animal Dimension
INSERT INTO animal_dim ("Animal ID", "Name", "Animal Type", "Breed", "Color", "Sex", "DOB")
SELECT DISTINCT "Animal ID", "Name", "Animal Type", "Breed", "Color", "Sex", "DOB"
FROM outcomes_staging
WHERE "Animal ID" IS NOT NULL;

--- Outcomes Dimension
INSERT INTO outcome_type_dim ("Outcome Type")
SELECT DISTINCT "Outcome"
FROM outcomes_staging
WHERE "Outcome" IS NOT NULL;

--- Reproductive Status Dimension
INSERT INTO reproductive_status_dim ("Reproductive Status")
SELECT DISTINCT "Reproductive Status"
FROM outcomes_staging
WHERE "Reproductive Status" IS NOT NULL;

--- Date Dimension
INSERT INTO date_dim ("Date ID", "Day", "Month", "Year")
SELECT DISTINCT "Date ID", "Day", "Month", "Year"
FROM outcomes_staging
WHERE "Date ID" IS NOT NULL;




--- INSERT DATA INTO FACT TABLE
INSERT INTO outcomes_fct ("Date", "Animal", "Outcome", "Repo Status")
SELECT 
    dd."Date ID",
    ad."Animal ID",
    otd."Outcome ID",
    rsd."Status ID"
FROM outcomes_staging os
JOIN date_dim dd ON os."Date ID" = dd."Date ID"
JOIN animal_dim ad ON os."Animal ID" = ad."Animal ID"
JOIN outcome_type_dim otd ON os."Outcome" = otd."Outcome Type"
JOIN reproductive_status_dim rsd ON os."Reproductive Status" = rsd."Reproductive Status";

[2023-11-22T05:47:52.666+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 275, in execute
    hook = self.get_db_hook()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 186, in get_db_hook
    return self._hook
  File "/usr/local/lib/python3.8/functools.py", line 967, in __get__
    val = self.func(instance)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 148, in _hook
    conn = BaseHook.get_connection(conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/connection.py", line 477, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `lab3_postgres_connection` isn't defined
[2023-11-22T05:47:52.669+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=outcomes_dag, task_id=Insert, execution_date=20231122T054734, start_date=20231122T054752, end_date=20231122T054752
[2023-11-22T05:47:52.676+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 29 for task Insert (The conn_id `lab3_postgres_connection` isn't defined; 202)
[2023-11-22T05:47:52.706+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-22T05:47:52.721+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
